environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: 'cmd /E:ON /V:ON /C .\tools\appveyor\run_with_env.cmd'
    ANACONDA_TOKEN:
      secure: 4tBu5qS0545E1dJt/t1aKIjI84gUjMGy/VQj/CKqwYNMzwM51dCemTLEv4Xwhy54
    PROJECT_NAME: biomes
    GITHUB_REPO_NAME: jpn--/biomes
    PYPACKAGE: larch

  matrix:
    - PYTHON_VERSION: 3.7
      CONDA: C:\Miniconda37

image: Visual Studio 2015

# For testing only...
#skip_non_tags: true

platform:
  - x64

branches:
  only:
    - master

init:
  - echo "begin init"
  - ps: if ($Env:PLATFORM -eq "x64") { $Env:CONDA = "${Env:CONDA}-x64" }
  - ps: Write-Host $Env:PYTHON_VERSION
  - ps: Write-Host $Env:CONDA
  - ps: Write-Host $Env:GITHUB_REPO_NAME
  - ps: Write-Host $Env:PLATFORM
  - ps: Write-Host $Env:APPVEYOR_REPO_TAG
  - ps: Write-Host $Env:APPVEYOR_REPO_TAG_NAME
  - ps: Write-Host $Env:APPVEYOR_REPO_NAME

install:
  - echo "begin install"
  # Make sure the compiler is accessible
  - '"%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%'

  # Load the conda root environment, configure and install some packages
  - '"%CONDA%\Scripts\activate.bat"'
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  
  # Fix error with juntion points, see https://github.com/appveyor/ci/issues/2270
  - mklink /J C:\Miniconda3 C:\Miniconda37
  - mklink /J C:\Miniconda3-x64 C:\Miniconda37-x64
  
  # Show conda info for debugging
  - conda info -a
  - conda env create -f=taiga.yml

build: off

test_script:
  - echo "begin test"
  # - '"%CONDA%\Scripts\activate.bat"'

  - conda activate taiga
  - conda list
  - pytest --pyargs larch -v
  - pytest --pyargs geopandas --ignore-glob='*/test_geodataframe.py' --ignore-glob='*/test_overlay.py'

  # Run the tests outside the source tree.
  #- pushd "%HOMEPATH%" && (conda activate taiga & pytest --pyargs larch -v & popd)
  #- pushd "%HOMEPATH%" && (conda activate taiga & pytest --pyargs geopandas --ignore-glob='*/test_geodataframe.py' --ignore-glob='*/test_overlay.py' & popd)


on_success:
  - ECHO "Yep"

